### PR TITLE
Update ddos.py

### PR DESCRIPTION
**Pull request by RiskVirusPro**
solve issue #174 #175

### CODE REVIEW

**Comment by ZoZomk6** [comment]
> solve issue #174 #175

It doesn't work for me

**Comment by OishiiCha** [comment]
Having an issue in the tools/ddos.py file, line29
subprocess.run([
            "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])

It errors on socks_type5.4.1

**Comment by OishiiCha** [comment]
update fixed:
subprocess.run([
            "sudo", "python3 ddos", method, url, "socks_type5.4.1", threads, proxylist, multiple, timer])

**Review by loloboin — APPROVED** [review]

**Comment by stefancandrea** [comment]
Merge this please!

**Comment by mightyNoseHairs** [comment]
same issue on latest version

**Comment by mokrunka** [comment]
@Z4nzu, my friend, could you merge this PR for us?

**Review by mokrunka — APPROVED** [review]

**Review by spacecowboy012424 — APPROVED** [review]
Awesome job

**Comment by cclauss** [comment]
The current code is a Python Syntax Error so please merge this pull request.

$ `flake8 . --count --select=E9,F63,F7,F8 --show-source --statistics`
```
./hackingtool/tools/ddos.py:29::51: E999 SyntaxError: invalid syntax. Perhaps you forgot a comma?
            "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                  ^
1     E999 SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Review by pl9527 — COMMENTED** [review]
1111

**Comment by EgirlDestroyer** [comment]
Fix it yourself, I'm not gonna sit for 40 minutes straight to merge a
fucking code

**Comment by mokrunka** [comment]
You are aware that we have "fixed it ourselves", and we're merely trying to get the repo owner to merge the fixes into the master branch, right?

**Comment by caio13m** [comment]
Fixed (:

https://github.com/caio13m/hackingtoolV

**Pull request merged**
