### PR TITLE
Make it executable & configurable on macOS

### PR DESCRIPTION
**Pull request by Northernside**
I'm really lazy to be honest, but I managed to get it running & configurable (the path screen at the first start) under macOS with this PR.
I'm sorry if there are some critical issues/no-go's or just some weird code as I've never touched neither Python code nor bash scripts in my life (well, I've used them, but I've not written them by myself).
I didn't test the functionalities though, but I can confirm that navigating through the menus is at least working :)

image

### CODE REVIEW

**Comment by Northernside** [comment]
okay, basically nothing works lol, maybe someone wants to make all tools compatible because I don't :)

**Review by Wethepeopledidit — APPROVED** [review]
Please https://instagram.com/gvo.autumn?igshid=YWJhMjlhZTc= #330

**Comment by Northernside** [comment]
that was a weird comment lmao

**Comment by giacara** [comment]
szjhcvudszgbvcjdfuv

**Comment by giacara** [comment]
gdergrgvf

**Pull request closed without merging**
