### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by hackerboy9**
This pull request adds a  badge to the . This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about Repl.it [here](https://repl.it).

### CODE REVIEW

**Comment by naveennamani** [comment]
thanks for the pull request, can you please update readme.md file also by running generate_readme.py script

**Comment by Linkid** [comment]
This user did the same PR in fofix/fofix#225 with no answer…

**Comment by naveennamani** [comment]
> This user did the same PR in fofix/fofix#225 with no answer…

in that case it's better to close this pull request too, thanks for the info

**Comment by Z4nzu** [comment]
> This user did the same PR in fofix/fofix#225 with no answer…

Hello, yes I saw it in many repositories that he had did same things in all the others repo. And I had checked it. It's not possible to run on repl because this tool not wouldn't work without SU permission and that site doesn't allow. So here I'm going to close it.

Thanks @naveennamani @Linkid

**Pull request closed without merging**
