### PR TITLE
Create uninstall.sh

### PR DESCRIPTION
**Pull request by Swetsen**
im bored rn so I made an uninstaller. Idk if this works but this should uninstall all traces of the program

### CODE REVIEW

**Comment by sudokit** [comment]
Would probably be better to add its own option in install.sh

**Comment by Z4nzu** [comment]
Hii, Please add more details for the commit I need more clarity before merging branch.

**Review by Ep262626 — COMMENTED** [review]
What’s this for

**Comment by uttamsachapara** [comment]
Want Annonyomous Sms sending repository ...refer some for termux

**Pull request closed without merging**
