### PR TITLE
dnstwist

### PR DESCRIPTION
**Pull request by MDA1422**
add dnstwist

### CODE REVIEW

**Review by MDA1422 — COMMENTED** [review]
i think this tool is good

**Comment by MDA1422** [comment]
i think this tool is good

**Review by Z4nzu — APPROVED** [review]

**Comment by vilonee** [comment]
yo does this all in one hack legit

**Comment by vilonee** [comment]
yo is this legit

**Comment by MDA1422** [comment]
> yo is this legit

what do you mean

**Comment by Arslan-12345** [comment]
yes it is

**Pull request merged**
